# Generated by Django 2.2.2 on 2019-06-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_cond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=30)),
                ('course_name', models.CharField(max_length=30)),
            ],
        ),
    ]
