# Generated by Django 2.2.2 on 2019-06-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_cond_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_cond',
            name='info',
        ),
    ]
