# Generated by Django 2.2.2 on 2019-06-29 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_course_cond_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_cond',
            name='info',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course_info'),
        ),
    ]
