# Generated by Django 2.2.2 on 2019-06-29 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20190629_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_cond',
        ),
    ]
