# Generated by Django 2.2.2 on 2019-06-29 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_delete_course_cond'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_cond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('grade', models.IntegerField()),
                ('info', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course_info')),
            ],
        ),
    ]
