# Generated by Django 2.2.2 on 2019-06-29 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_cond'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_cond',
            name='info',
        ),
    ]
